slug = "i"
number = 1
title = "Issue 1"

[[article]]
path = "/announcing"
file = "announcing.md"
title = "Announcing Rust Magazine"
author = "folyd"
pub_date = "2022-12-10"
publish = true
featured = true
